function Treadwall_predictable
%

global BpodSystem

%% ---------- IPC setup ---------------------------------------------------
ipc_dir = gui_ipc_dir();
gui_session_init(ipc_dir);

%% ---------- Define task parameters --------------------------------------
start_path = BpodSystem.Path.DataFolder; % folder selected in GUI;

% initialize parameters
S = struct();

% load correct parameters for location
location = questdlg('Where do you perform your experiments?',...
    'Locations',...
    'BN','ISR','ISR');
params_file = fullfile([BpodSystem.Path.ProtocolFolder '\treadwall_scrambled_parameters_', location, '.m']);
run(params_file)
fprintf('Parameters loaded for: %s \n', location);

% ------ GUI parameters
S.GUI.SubjectID = BpodSystem.GUIData.SubjectName;
S.GUI.SessionID = BpodSystem.GUIData.SessionID;
S.GUI.ITIDur = ITIDur; %in seconds
S.GUI.ScalingFactor = 1;
S.GUI.EmergencyStop = 'SendBpodSoftCode(2)';
S.GUIMeta.EmergencyStop.Style = 'pushbutton';

session_dir = ([start_path '\' S.GUI.SubjectID '\' S.GUI.SessionID]);
animal_dir = ([start_path '\' S.GUI.SubjectID]);

BpodParameterGUI('init', S);
BpodSystem.ProtocolSettings = S;
try close(BpodSystem.ProtocolFigures.ParameterGUI); catch, end

% Publish the protocol-loaded parameters so the GUI shows them as its initial
% spinbox values (predictable exposes ITIDur + ScalingFactor, no stimDur).
gui_publish_loaded_params(ipc_dir, S);

%% ---------- Trials ------------------------------------------------------
% get base name
if isfield(BpodSystem.GUIData, 'DatetimeStr') && ~isempty(BpodSystem.GUIData.DatetimeStr)
    % Use datetime from the GUI if available, so all file names match
    datetime_str = BpodSystem.GUIData.DatetimeStr;
else
    datetime_str = datestr(now, 'yyyymmdd_HHMM');
end
base_name = sprintf('%s_%s', S.GUI.SubjectID, datetime_str);

% load zones
if exist(fullfile([animal_dir base_name '_zones.csv']), 'file')
    zones_dir = fullfile([animal_dir base_name '_zones.csv']);
    fprintf('Zones have been loaded from %s\n', zones_dir);
else
    zones_dir = create_zones(animal_dir);
end

zones = readtable(zones_dir);
zones = zones.type;

stimOutput = cell(1,length(zones));
for i = 1:length(zones)
    stimOutput{i} = GetStimOutput(zones{i});
end

% one trial will be defined as one lap on the treadmill
% maximum 100 laps per session
S.GUI.MaxTrialNumber = 100;

%% ---------- Arduino Synchronizer ----------------------------------------
COM = 'COM9';
try
    arduino = serialport(COM, 115385);
catch
    error('The Arduino is not connected to %s, select the correct COM!', COM)
end

% Send initial scaling value to Arduino
scalingValue = S.GUI.ScalingFactor;
writeline(arduino, strcat(num2str(scalingValue), '\n'));
lastScalingFactor = scalingValue;

%% ---------- Rotary Encoder Module ---------------------------------------
try
    R = RotaryEncoderModule(BpodSystem.ModuleUSB.RotaryEncoder1);
catch
    error(['The Rotary Encoder Module is not coupled to the correct COM, ' ...
        'check the Bpod Console!'])
end

R.thresholds = [-5,5];
R.sendThresholdEvents = 'On';
R.enableThresholds([1,1])

%R.startUSBStream() -> moved to after restarting timer for proper alignment
%R.streamUI() % for live streaming position, good for troubleshooting

%% ---------- Analog Output Module ----------------------------------------
try
    W = BpodWavePlayer(BpodSystem.ModuleUSB.WavePlayer1);
catch
    error(['The Analog Output Module is not coupled to the correct COM, ' ...
        'check the Bpod Console!'])
end

W.SamplingRate = 100;%in kHz
W.OutputRange = '0V:5V';
W.TriggerMode = 'Master';

% Waveforms for distances
lengthWave = 1800*W.SamplingRate; %maximum length of session
for i = 1:length(waveforms)
    W.loadWaveform(i, waveforms{i}*ones(1,lengthWave));
end

%% ---------- Analog Input Module ----------------------------------------
try
    A = BpodAnalogIn(BpodSystem.ModuleUSB.AnalogIn1);
catch
    error(['The Analog Input Module is not coupled to the correct COM, ' ...
        'check the Bpod Console!'])
end

A.SamplingRate = 100;%in kHz
A.nActiveChannels = 3;
A.InputRange = {'0V:10V', '0V:10V', '0V:10V', '0V:10V', '0V:10V', '0V:10V', '0V:10V', '0V:10V'};
A.Thresholds(1,1:3) = [4.0, 2.5, 1.5];
A.ResetVoltages(1,1:3) = [3.2, 1.65, 1.65]; % TO DO: check reset voltage for first trigger
A.SMeventsEnabled(1,1:3) = [1, 1, 1];
A.startReportingEvents()

%A.scope() % for live streaming inputs, good for troubleshooting

%% ---------- Restart Timer -----------------------------------------------
% Discard any stale bytes left in the Bpod serial buffer (e.g. after an
% emergency stop) so the clock-reset confirmation byte is read correctly.
nStale = BpodSystem.SerialPort.bytesAvailable;
if nStale > 0, BpodSystem.SerialPort.read(nStale, 'uint8'); end
BpodSystem.SerialPort.write('*', 'uint8');
Confirmed = BpodSystem.SerialPort.read(1,'uint8');
if Confirmed ~= 1
    error('Faulty clock reset')
end

% start rotary encoder stream
R.startUSBStream()

%% ---------- Emergency-stop watcher --------------------------------------
% Poll for the GUI emergency-stop flag
% onCleanup guarantees the timer is removed on every exit path (normal end, early return, or error).
t_estop = gui_start_estop_timer(ipc_dir);
estopCleanup = onCleanup(@() stop_estop_timer(t_estop));

%% ---------- Synching with WaveSurfer ------------------------------------
sma = NewStateMachine();
sma = AddState(sma, 'Name', 'WaitForWaveSurfer', ...
    'Timer',0,...
    'StateChangeConditions', {'BNC1High', 'exit', 'SoftCode2', 'exit'},...
    'OutputActions', {'WavePlayer1', ['!' 3 0 0]});
SendStateMachine(sma);
disp('Waiting for Wavesurfer...');
RawEvents = RunStateMachine;

if ~isempty(fieldnames(RawEvents)) % If trial data was returned
    BpodSystem.Data = AddTrialEvents(BpodSystem.Data,RawEvents); % Computes trial events from raw data
    SaveBpodSessionData; % Saves the field BpodSystem.Data to the current data file
end

% Clean exit if user stopped Bpod while waiting for WaveSurfer.
if BpodSystem.Status.BeingUsed == 0
    disp('Session stopped while waiting for WaveSurfer. Exiting cleanly.');
    W.setFixedVoltage([1 2], 0);
    R.stopUSBStream();
    gui_signal_done(ipc_dir);
    return
end

disp('Synced with Wavesurfer.');

%% ---------- Main Loop ---------------------------------------------------
% start timer in Matlab, session ends if timer is up or 100 laps have been run
tpredict = timer;
tpredict.StartDelay = 1200;
tpredict.TimerFcn = "SendBpodSoftCode(1)";
tpredict.StartFcn = "fprintf('timer started\n')";

start(tpredict)
for currentTrial = 1:S.GUI.MaxTrialNumber
    disp(' ');
    disp('- - - - - - - - - - - - - - - ');
    disp(['Loop: ' num2str(currentTrial) ' - ' datestr(now,'HH:MM:SS')]);

    % Read live parameter edits from the GUI
    S = gui_read_params(S, ipc_dir);

    % Get current Scaling value
    scalingValue = S.GUI.ScalingFactor;
    % If changed, update Arduino
    if scalingValue ~= lastScalingFactor
        writeline(arduino, strcat(num2str(scalingValue), '\n'));
        lastScalingFactor = scalingValue;
        fprintf('Updated Arduino with new ScalingFactor: %.1f \n', scalingValue);
    end

    % construct state machine
    sma = NewStateMachine();

    %first trial: with start buffer
    if currentTrial == 1
        sma = AddState(sma, 'Name', 'StartBuffer', ...
            'Timer', S.GUI.ITIDur,...
            'StateChangeConditions', {'Tup', 'readDirection', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', ['!' 3 0 0]});

        sma = AddState(sma, 'Name', 'readDirection', ...
            'Timer', 0,...
            'StateChangeConditions', {'RotaryEncoder1_2', 'z1f', 'RotaryEncoder1_1', 'z1b', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', ['!' 3 0 0],'RotaryEncoder1', 'ZE'});

        % zone 1
        sma = AddState(sma, 'Name', 'z1f',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z2f', 'AnalogIn1_3', 'z1b', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{1}});
        sma = AddState(sma, 'Name', 'z1b',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z4bb', 'AnalogIn1_2', 'z1f', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{1}});

        % zone 2
        sma = AddState(sma, 'Name', 'z2f',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z3f', 'AnalogIn1_3', 'z2b', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{2}});
        sma = AddState(sma, 'Name', 'z2b',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z1b', 'AnalogIn1_2', 'z2f', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{2}});
        sma = AddState(sma, 'Name', 'z2fb',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z3fb', 'AnalogIn1_3', 'z2bb', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{2}});
        sma = AddState(sma, 'Name', 'z2bb',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z1b', 'AnalogIn1_2', 'z2fb', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{2}});

        % zone 3
        sma = AddState(sma, 'Name', 'z3f',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z4f', 'AnalogIn1_3', 'z3b', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{3}});
        sma = AddState(sma, 'Name', 'z3b',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z2b', 'AnalogIn1_2', 'z3f', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{3}});
        sma = AddState(sma, 'Name', 'z3fb',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z4fb', 'AnalogIn1_3', 'z3bb', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{3}});
        sma = AddState(sma, 'Name', 'z3bb',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z2bb', 'AnalogIn1_2', 'z3fb', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{3}});

        % zone 4: exit trial after completing zone 4
        sma = AddState(sma, 'Name', 'z4f',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','exit', 'AnalogIn1_3', 'z4b', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{4}});
        sma = AddState(sma, 'Name', 'z4b',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z3b', 'AnalogIn1_2', 'z4f', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{4}});
        sma = AddState(sma, 'Name', 'z4fb',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z1f', 'AnalogIn1_3', 'z4bb', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{4}});
        sma = AddState(sma, 'Name', 'z4bb',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z3bb', 'AnalogIn1_2', 'z4fb', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{4}});

        % reached timer
        sma = AddState(sma, 'Name', 'EndBuffer',...
            'Timer', 10,...
            'StateChangeConditions', {'Tup', 'StopCamera', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', ['!' 3 0 0]});

        sma = AddState(sma, 'Name', 'StopCamera', ...
            'Timer', 1,...
            'StateChangeConditions', {'Tup', 'exit'},...
            'OutputActions', {'BNC1',1});

    % last trial: with end buffer
    elseif currentTrial == S.GUI.MaxTrialNumber
        % zone 1
        sma = AddState(sma, 'Name', 'z1f',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z2f', 'AnalogIn1_3', 'z1b', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{1}});
        sma = AddState(sma, 'Name', 'z1b',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z4bb', 'AnalogIn1_2', 'z1f', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{1}});

        % zone 2
        sma = AddState(sma, 'Name', 'z2f',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z3f', 'AnalogIn1_3', 'z2b', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{2}});
        sma = AddState(sma, 'Name', 'z2b',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z1b', 'AnalogIn1_2', 'z2f', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{2}});
        sma = AddState(sma, 'Name', 'z2fb',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z3fb', 'AnalogIn1_3', 'z2bb', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{2}});
        sma = AddState(sma, 'Name', 'z2bb',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z1b', 'AnalogIn1_2', 'z2fb', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{2}});

        % zone 3
        sma = AddState(sma, 'Name', 'z3f',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z4f', 'AnalogIn1_3', 'z3b', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{3}});
        sma = AddState(sma, 'Name', 'z3b',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z2b', 'AnalogIn1_2', 'z3f', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{3}});
        sma = AddState(sma, 'Name', 'z3fb',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z4fb', 'AnalogIn1_3', 'z3bb', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{3}});
        sma = AddState(sma, 'Name', 'z3bb',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z2bb', 'AnalogIn1_2', 'z3fb', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{3}});

        % zone 4: exit experiment after completing zone 4
        sma = AddState(sma, 'Name', 'z4f',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','EndBuffer', 'AnalogIn1_3', 'z4b', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{4}});
        sma = AddState(sma, 'Name', 'z4b',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z3b', 'AnalogIn1_2', 'z4f', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{4}});
        sma = AddState(sma, 'Name', 'z4fb',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z1f', 'AnalogIn1_3', 'z4bb', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{4}});
        sma = AddState(sma, 'Name', 'z4bb',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z3bb', 'AnalogIn1_2', 'z4fb', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{4}});

        % exit experiment
        sma = AddState(sma, 'Name', 'EndBuffer',...
            'Timer', 10,...
            'StateChangeConditions', {'Tup', 'StopCamera', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', ['!' 3 0 0]});

        sma = AddState(sma, 'Name', 'StopCamera', ...
            'Timer', 1,...
            'StateChangeConditions', {'Tup', 'exit'},...
            'OutputActions', {'BNC1',1});

    else
        % zone 1
        sma = AddState(sma, 'Name', 'z1f',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z2f', 'AnalogIn1_3', 'z1b', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{1}});
        sma = AddState(sma, 'Name', 'z1b',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z4bb', 'AnalogIn1_2', 'z1f', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{1}});

        % zone 2
        sma = AddState(sma, 'Name', 'z2f',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z3f', 'AnalogIn1_3', 'z2b', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{2}});
        sma = AddState(sma, 'Name', 'z2b',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z1b', 'AnalogIn1_2', 'z2f', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{2}});
        sma = AddState(sma, 'Name', 'z2fb',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z3fb', 'AnalogIn1_3', 'z2bb', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{2}});
        sma = AddState(sma, 'Name', 'z2bb',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z1b', 'AnalogIn1_2', 'z2fb', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{2}});

        % zone 3
        sma = AddState(sma, 'Name', 'z3f',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z4f', 'AnalogIn1_3', 'z3b', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{3}});
        sma = AddState(sma, 'Name', 'z3b',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z2b', 'AnalogIn1_2', 'z3f', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{3}});
        sma = AddState(sma, 'Name', 'z3fb',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z4fb', 'AnalogIn1_3', 'z3bb', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{3}});
        sma = AddState(sma, 'Name', 'z3bb',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z2bb', 'AnalogIn1_2', 'z3fb', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{3}});

        % zone 4: exit trial after completing zone 4
        sma = AddState(sma, 'Name', 'z4f',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','exit', 'AnalogIn1_3', 'z4b', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{4}});
        sma = AddState(sma, 'Name', 'z4b',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z3b', 'AnalogIn1_2', 'z4f', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{4}});
        sma = AddState(sma, 'Name', 'z4fb',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z1f', 'AnalogIn1_3', 'z4bb', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{4}});
        sma = AddState(sma, 'Name', 'z4bb',...
            'Timer',0,...
            'StateChangeConditions', {'AnalogIn1_1','z3bb', 'AnalogIn1_2', 'z4fb', 'SoftCode1', 'EndBuffer', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', stimOutput{4}});

        % reached timer
        sma = AddState(sma, 'Name', 'EndBuffer',...
            'Timer', 10,...
            'StateChangeConditions', {'Tup', 'StopCamera', 'SoftCode2', 'StopCamera'},...
            'OutputActions', {'WavePlayer1', ['!' 3 0 0]});

        sma = AddState(sma, 'Name', 'StopCamera', ...
            'Timer', 1,...
            'StateChangeConditions', {'Tup', 'exit'},...
            'OutputActions', {'BNC1',1});
    end

    % run state machine
    SendStateMachine(sma);
    RawEvents = RunStateMachine;

    if ~isempty(fieldnames(RawEvents)) % If trial data was returned
        BpodSystem.Data = AddTrialEvents(BpodSystem.Data,RawEvents); % Computes trial events from raw data
        BpodSystem.Data.TrialSettings(currentTrial) = S;
        BpodSystem.Data.Loop(currentTrial) = currentTrial;
        SaveBpodSessionData; % Saves the field BpodSystem.Data to the current data file
        %SaveBpodProtocolSettings;
    end

    if strcmp(tpredict.Running, 'off')
        % timer is over
        fprintf('timer stopped\n')
        W.setFixedVoltage([1 2], 0)
        delete(tpredict)
        break

    elseif BpodSystem.Status.BeingUsed == 0
        % emergency stop
        disp('Session stopped (emergency stop or Bpod Console). Partial trial data saved.')
        W.setFixedVoltage([1 2], 0)
        stop(tpredict)
        delete(tpredict)
        break

    elseif currentTrial == S.GUI.MaxTrialNumber
        % maximum trial num reached
        W.setFixedVoltage([1 2], 0)
        stop(tpredict)
        delete(tpredict)
    end
end

clear arduino
disp('Loop end');

disp('Saving Rotary Encoder Data...')
RotData = R.readUSBStream();
save([session_dir '\RotData'],'RotData')
R.stopUSBStream()

BpodSystem.Status.BeingUsed = 0;
try close(BpodSystem.ProtocolFigures.ParameterGUI); catch, end

% Signal the GUI: session complete, stop WaveSurfer
gui_signal_done(ipc_dir);
disp('Session complete. WaveSurfer stopping automatically.');
end